os:
  - linux
  - osx

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - rpm

git:
  depth: 5

language: node_js

node_js:
  - 8.11.2

before_install:
  - npm i -g npm@6.0.1
  - npm install gulp -g

script:
  - gulp release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gulp release --chromeos; fi

cache:
  directories:
  - node_modules

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - $(git ls-files -o -x node_modules/ | tr "\n" ":")
    target_paths:
      - /$TRAVIS_BUILD_NUMBER/
