language: node_js

node_js:
  - "node"

addons:
  artifacts:
    s3_region: "us-west-2"

before_install:
  - npm install gulp -g

script:
  - npm install
  - gulp release

cache:
  directories:
  - node_modules
